### ISSUE TITLE
multiple file format for each record

### ISSUE THREAD

**Issue by ClauLung** [dana-apps/dana-core#162]
there should be only one media file links to each record, but would be great if we could have a 'duplicate' button to copy all the metadata and upload another media file

**Comment by lanehk** [comment]
Claudia - I think we can have multiple media files link to one record. However, I notice that the problem is we can only link images for now - can we do videos and PDFs?

**Comment by lanehk** [comment]
also - possible to show asset as a thumbnail please?

**Comment by conatus** [comment]
Thumbnail element over here - #172

**Comment by conatus** [comment]
Will split out into two further issues.

**Comment by conatus** [comment]
Split this into different issues that capture all requirements, so closing out.
