### ISSUE TITLE
New database-People

### ISSUE THREAD

**Issue by ClauLung** [dana-apps/dana-core#167]
When I create the new database people, 

1.  I cannot see the field 'description' that exists in other pre-created databases
2. I cannot set the field that's visible to public or for internal use only
![image](https://user-images.githubusercontent.com/95728978/204148453-5e775a86-6eeb-4aaa-be28-a37bec6906e5.png)
3. would like the people database to be able to set 'mechanism' like free text, authority list and auto-generated by combining Last Name (English), First Name (English), Last Name (Other Language), First Name (Other Language). Also enabling the possibility to overwrite by free-text 
Reference to https://docs.google.com/spreadsheets/d/1nZBnXv_n9p_4DwMAPvvh1gLc_nPixvE6BFDQJP5IT5s/edit?pli=1#gid=1829097081
![image](https://user-images.githubusercontent.com/95728978/204106930-0bdd95f9-274d-45cb-bcc3-b039d4b5fafc.png)

**Comment by conatus** [comment]
Will split into three separate issues to aid tracking.

**Comment by conatus** [comment]
All issues captured elsewhere, closing out.
