### ISSUE TITLE
Events should have ID

### ISSUE THREAD

**Issue by ClauLung** [dana-apps/dana-core#168]
When I create the event database , for EID, it should be auto-generated, how could I set this? 
![image](https://user-images.githubusercontent.com/95728978/204148543-93457ea7-2f95-4ac4-8baf-d170bd41a374.png)

**Comment by conatus** [comment]
@ClauLung 

Does the record ID you have in the Event do enough to serve this function as an ID? It is unique.

**Comment by conatus** [comment]
Closing as they do have an ID that is indeed auto-generated.
